# Generated by Django 4.2.2 on 2023-07-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pages', models.SmallIntegerField(max_length=4)),
                ('student', models.ManyToManyField(related_name='books', to='school.student')),
            ],
        ),
    ]
